### PR TITLE
first stab at creating adjustments

### PR DESCRIPTION
**Pull request by doon**
This is the first stab at creating adjustments from Line Items.   If an adjustment exists right now it will show status as pending.  if it doesn't exist, it offers a button to create one, which will pop down a modal and create the adjustment on the line item.  Creating the adjustment just creates it.  Doesn't really do anything else yet..    let me know what you think...

### CODE REVIEW

**Comment by jrabolli** [comment]
Doon

Can not thank you enough for today!  Meeting went well in the end.  I will tell you more tomorrow.  Do you have a rough idea of hours thus far in your end?  I don't need s bill yet but they are trying to account for time spent on health home total so far which includes portal work.  I assume it's for some report purposes.

**Comment by doon** [comment]
Sure thing. Never seen that happen before. The  again I am old school and generally make everything lower case so it hasn't bitten me.  

As for  hours quick look shows about 11 so far. 

-----------------
Patrick Muldoon

Typed with my thumbs on a mobile device please excuse any errors.

**Comment by jrabolli** [comment]
Thanks, just rough is all I need.  Lower case from now on here too!

**Comment by jrabolli** [comment]
hey, I was out of the office today and will be tomorrow as well (military).  i wanted to get a couple thoughts down from meeting before I forget them.  Overall it went well, thanks again for your jumping in - still don’t know exactly what he root cause was but luckily you got it up.  anyway - we mostly focused on invoice/adjustments as you would imagine.  

Because the data extract (actions) that we import has invoice ID’s and we create our own, they want us to include the invoice ID on our invoice (line_items) for reference.  I think they use the invoice ID’s from the system providing us the data for something in finance.  That should be easy

as far as the life cycle of the invoice goes (i spent the most time trying to get them to think about this and provide direction)… we decided we need a mechanism for locking the invoice and knowing that the negotiation/adjustments are over and we expect payment.  Essentially we decided that when a CMA looks at a new invoice they can either ‘accept’ it as is by pressing button or they can dispute a line item (adjustments).  Then is there are adjustments requested the admin would deal with those and ether basically do the same thing, accept/lock it or allow it to remain open because we expect more back and fourth.  Either way the point would be that either party could lock it by accepting or the CMA could create adjustments keeping it open for the time being.  Nobody can lock it while there are adjustments not satisfied (accept/deny) and a CMA can not re-open it once it has been close (by either side), the admin probably can.  Once its closed it is in a  sort of ‘awaiting payment’ type of status.

we need to add to the invoice a couple fields for the admin like check #, check amount, paid date for obvious reasons. admin would would manually enter these

as far as adjustments go….aside from the obvious like working on the ability for the admin to review adjustments and accept/deny and then recalculating the invoice.  the adjustments themselves were further clarified.  reasons are fine right now the way they are.  The fields they would be disputing or creating adjustments against however are hh_fee and mco_fee so those are the two fields we should put in the adjustment modal and allow for adjustment.  They would also like us to allow in the adjustment the ability for the CMA to add to the invoice, add a line item essentially.  But it can only be for a member (patient) that exists within that CMA.  So essentially that means hypothetically….

they decide to add a member/patient line item to the invoice 
they click an adjustment button maybe at the top of the invoice that reads ‘add member’ or something like that
first step on that model is a simple search for member
if member exists and they select it, they essentially get the action/new for that member which then becomes an adjust waiting for approval like any other
(something like that)

as far as the invoice logic goes, you are correct on the hh_fee + mco_fee and we will continue togged those.  we just need to be careful we are using the others filters such as the status, billable etc and the fact that some are moo_fee +hh_fee and some are just one of those fees.  We also have to add a little logic in the filters to remove dupes.  Apparently there is a rule that you can only bill for one action/touch/whatever per patient per month even though there are regularly multiple actions for the same patient within a month legitimately.  So I guess we have som logic to compare what we would expect for payment and always choose the higher :)

anyway, just wanted togged my thoughts down before I forget.  I have another meeting next Wednesday but I didn’t promise anything.  hopefully there is some progress though and I will continue to have meetings and keep them in the loop as we work things.  makes it all less contentious.

you should submit a bill soon, we are classic for slow paying and you have put it good time.

we can talk about tribal next week as time permits, long story short though - I think we have an opportunity if I could show them something.  Especially since we could likely ‘tie’ it to health home activities pretty easy if we wanted to.  That presents huge value and nobody else can do that.  We are writing a RFP right now for the clinical platform side of this (like tribal) and will be reviewing systems.

JR

**Pull request merged**
